<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="search" nsURI="http://data-in-motion.biz/search/1.0" nsPrefix="search">
  <eClassifiers xsi:type="ecore:EClass" name="IndexDataContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexData" upperBound="-1"
        eType="#//IndexData" containment="true" eKeys="#//IndexData/id"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//IndexDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workspaceProviderId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IndexDataType">
    <eLiterals name="FileSystem" literal="FS"/>
    <eLiterals name="MMap" value="1" literal="MMAP"/>
    <eLiterals name="RAM" value="2"/>
    <eLiterals name="MongoDB" value="3" literal="MONGODB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Descriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DescriptorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DescriptorType">
    <eLiterals name="INDEX"/>
    <eLiterals name="RESULT" value="1"/>
    <eLiterals name="QUERY" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptorContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptors" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="group"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryDescriptors" upperBound="-1"
        eType="#//Descriptor" volatile="true" transient="true" derived="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#descriptors"/>
        <details key="kind" value="QUERY"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexDescriptors" upperBound="-1"
        eType="#//Descriptor" volatile="true" transient="true" derived="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#descriptors"/>
        <details key="kind" value="INDEX"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultDescriptors" upperBound="-1"
        eType="#//Descriptor" volatile="true" transient="true" derived="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#descriptors"/>
        <details key="kind" value="RESULT"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexData" lowerBound="1"
        eType="#//IndexData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexDescriptors" upperBound="-1"
        eType="#//Descriptor" eKeys="#//Descriptor/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryDescriptors" upperBound="-1"
        eType="#//Descriptor" eKeys="#//Descriptor/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultDescriptors" upperBound="-1"
        eType="#//Descriptor" eKeys="#//Descriptor/id"/>
  </eClassifiers>
</ecore:EPackage>
